apiVersion: v1
kind: Namespace
metadata:
  name: example-service
---
apiVersion: v1
kind: Service
metadata:
  name: example-service-lb
  namespace: example-service
spec:
  externalTrafficPolicy: Local
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: example-service
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service
  namespace: example-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-service
  template:
    metadata:
      labels:
        app: example-service
    spec:
      containers:
      - image: devacrcompany.azurecr.io/example-service:dev-1.0
        imagePullPolicy: Always
        name: example-service
        ports:
        - containerPort: 8080
      nodeSelector:
        beta.kubernetes.io/instance-type: Standard_B2s

