apiVersion: apps/v1
# The kind of this file is deployment
kind: Deployment
# The tag of our server
metadata:
  name: __ServiceName__
  namespace: __ServiceName__
# The required deployment
spec:
  selector:
    matchLabels:
      app: __ServiceName__
  # Number of default replicas to deploy
  replicas: 1
  # The Pod desription
  template:
    metadata:
      labels:
        app: __ServiceName__
    spec:
      # The image which we will deploy
      containers:
        # The matches tag
        - name: __ServiceName__
          # The image location
          image: __imageName__
          imagePullPolicy: Always
          ports:
            - containerPort: __containerPort__
          envFrom:
            - secretRef:
                name: __ServiceName__-secret
          resources:
            limits:
              cpu: 500m
      nodeSelector:
        beta.kubernetes.io/instance-type: __InstanceType__
