apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: __ServiceName__-hpa
  namespace: __ServiceName__
spec:
  scaleTargetRef:
    kind: Deployment
    name: __ServiceName__
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
