apiVersion: v1

# K*S service for ingress/outgress
kind: Service
metadata:
  name: example-service-lb
  namespace: example-service
spec:
  # We wish to deploy Azure load balnacer
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: example-service
  ports:
    # The desired port for host and onctainer
    - name: "8080"
      protocol: TCP
      port: 8080
      targetPort: 8080

