kind: Service
apiVersion: v1
metadata:
  name: example-service
  namespace: example-service
spec:
  selector:
    app: example-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: "8080"
      port: 8080
      targetPort: 8080